Event search engine
agregacja-sda-team-12/eventy pull request #26
Opened 2019-03-24 12:41 UTC by adrian92a

finding posts in search engine by user nick

2019-03-24 12:47 UTC, adrian92a commented
Search posts by author nick

2019-03-24 13:23 UTC, towczare commented on src/main/java/pl/net/rogala/eventy/controller/EventController.java
> +    @Autowired
Lepiej rozbudować konstruktor o nowy parametr. 
Raz, że powinniśmy stosować spójną konwencję czy wstrzykujemy przez pola czy przez konstruktor. Po drugie konstruktor jest zwyczajnie lepszym wyborem bo definiuje jakie zależności są wymagane (przydatne chociażby w przypadku pisania testów dla danej klasy)

2019-03-24 13:23 UTC, towczare commented on src/main/java/pl/net/rogala/eventy/controller/EventController.java
> +        findEventDto.setOwnerName(ownerName);
Czemu setujemy ownera dwa razy? ;-)

2019-03-24 13:23 UTC, towczare commented on src/main/java/pl/net/rogala/eventy/model/FindEventDto.java
> +    private User owners;
Owners czy owner?
Zakładam że chodzi o to drugie ;-)

2019-03-24 13:23 UTC, towczare commented on src/main/java/pl/net/rogala/eventy/model/FindEventDto.java
> +        this.owners = owners;
Też do zmiany na liczbę pojedynczą

2019-03-30 10:57 UTC, towczare requested changes

2019-03-30 10:57 UTC, towczare commented on src/main/java/pl/net/rogala/eventy/configuration/BasicConfiguration.java
> +//ola@nowak.pl
Jakieś stare komentarze, raczej niepotrzebne.

2019-03-30 10:57 UTC, towczare commented on src/main/java/pl/net/rogala/eventy/controller/CommentController.java
> +        System.out.println("jest ok---------------------");
Wygląda na debug, starajmy się nie commitować takich rzeczy, ewentualnie jak już, zastąpić loggerem.

2019-03-30 10:57 UTC, towczare commented on src/main/java/pl/net/rogala/eventy/controller/EventController.java
> +    private UserRepository userRepository;
Nie powinniśmy omijać warstw i wrzucać repozytoriów bezpośrednio do controllera. Lepiej dorzucić tutaj zależność od userService.

2019-03-30 10:57 UTC, towczare commented on src/main/java/pl/net/rogala/eventy/controller/EventController.java
>  //        model.addAttribute("users", eventService.showAllUsersAssignedToEvent(Long.parseLong(eventId)));
Do wywalenia komentarze :-)

2019-03-30 10:57 UTC, towczare commented on src/main/java/pl/net/rogala/eventy/service/CommentService.java
> +    {
Niespójne formatowanie, nawiasy otwierajcie w linii powyżej. Drobnostka ale kuje w oczy i powoduje, że czytanie kodu jest trudniejsze bo nie trzyma wspólnego stylu formatowania.

2019-03-30 10:57 UTC, towczare commented on src/main/java/pl/net/rogala/eventy/service/CommentService.java
> +    {
Jak powyżej.

2019-03-30 10:57 UTC, towczare commented on src/main/resources/templates/event/showSingleEvent.html
> +            <!--<form method="get" th:action="@{/event/{id}/comment/{commentId}/editComment(commentId=${comment.id},id=${comment.eventId})}">-->
Komentarz, do wywalenia.

2019-03-30 12:41 UTC, towczare approved these changes

2019-03-30 12:42 UTC, merged